### PR TITLE
feat: Support Spring Boot native image

### PR DESCRIPTION
**Pull request by Christopher-Chianelli**
## Description of the change

Modifications required for Spring Boot Native image to work.
Requires https://github.com/TimefoldAI/timefold-solver/pull/609

Solving, terminate solving, and score explanations works in native mode. Solving is slow due to the GraalVM handling of record classes (see https://github.com/TimefoldAI/timefold-solver/pull/540 ; waiting for a new GraalVM release with the issue fixed).

### Development

- [ ] The changes have been covered with tests, if necessary.
- [ ] You have a green build, with the exception of the flaky tests.
- [ ] UI and JS files are fully tested, the user interface works for all modules affected by your changes (e.g., solve and analyze buttons).
- [ ] The network calls work for all modules affected by your changes (e.g., solving a problem).
- [ ] The console messages are validated for all modules affected by your changes.

### Code Review

- [ ] This pull request includes an explanatory title and description.
- [ ] The GitHub issue is linked.
- [ ] At least one other engineer has approved the changes.
- [ ] After PR is merged, inform the reporter.

### CODE REVIEW

**Comment by Christopher-Chianelli** [comment]
Performance numbers; workaround is cherry-picking the commit from https://github.com/TimefoldAI/timefold-solver/pull/540 onto https://github.com/TimefoldAI/timefold-solver/pull/609. The solver is run for 30 seconds. Results are extremely surprising:

| Description                            | Score Calculation Speed |
| -------------------------------------  | --------------------------------- |
|  Non-native (no workaround) | 58528/sec                       |
| Non-native (workaround)       | 70902/sec                       |
| Native (no workaround)         | 2666/sec                         |
| Native (workaround)              | 127527/sec                     |

**Comment by triceo** [comment]
The performance results are really surprising. Let's leave aside the native slowdown without the workaround - we know why that is. I am surprised first of all by the non-native performance; I wouldn't have merged the changes if I saw such a performance drop. (I tolerate ~4 %, not 20 %.) I need to investigate that further.

The fact that native performance is the best one whatsoever is equally surprising. Typically they are on par, or slightly worse. Maybe there were some upgrades to GraalVM which we didn't notice, and we should update our assumptions.

**Comment by Christopher-Chianelli** [comment]
Decided to test the production builds of spring and quarkus, and the numbers makes more sense.

| Description                                                             | Score Calculation Speed |
| ----------------------------------------------------------------  | --------------------------------- |
| Non-native (dev + no workaround)                        | 58528/sec                        |
| Non-native (dev + workaround)                              | 70902/sec                       |
| Non-native (production + no workaround)              | ~210000/sec                   |
| Non-native (production + workaround)                   | ~210000/sec                   |
| Native (no workaround)                                          | 2666/sec                         |
| Native (workaround)                                               | 127527/sec                     |

So for production builds, workaround has no affect, but in development mode, it does. Moreover, in development mode, the solver is ~3.5 times slower on my machine.

**Comment by Christopher-Chianelli** [comment]
Found the cause:
`mvn spring-boot:run` and `mvn quarkus:dev` will both disable the C2 compiler by passing the option `-XX:TieredStopAtLevel=1` to the JVM.
For spring boot, this can be disabled with this configuration:
```xml
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <configuration>
        <optimizedLaunch>false</optimizedLaunch>
    </configuration>
</plugin>
```
I don't know how to disable it for `quarkus:dev` though.

**Review by triceo — APPROVED** [review]

**Pull request merged**
