### PR TITLE
fix:Renaming variable names for collection types

### LINKED ISSUE #19: Rename fields "barList" to "bars" (quickstarts only)
- [ ] All quickstarts
- [ ] Quickstart guide docs

### PR DESCRIPTION
**Pull request by zepfred**
This pull request updates variable names for collection types using the following patterns: `<name>List`, `<name>Set`, and `<name>Map`.

Regarding the `timefold-solver` repository, only the name `shiftList` needs to be updated, and I'll create a separate PR to address that.

Issue #19

### CODE REVIEW

**Comment by zepfred** [comment]
@triceo, the UI files were updated and tested. The PR is ready for your review.

**Comment by triceo** [comment]
When I run the Spring Boot example, I get this when I click on score analysis button:

image

The only suspicious thing in the log: 

    WARN [nio-8080-exec-4] Resolved [org.springframework.web.bind.MissingServletRequestParameterException: Required request parameter 'fetchPolicy' for method parameter type ScoreAnalysisFetchPolicy is not present]

The issue is _not_ present in the Kotlin quickstart or the Quarkus quickstart.

**Review by triceo — CHANGES_REQUESTED** [review]
Spring Boot quickstart is partially broken. (Possibly unrelated to this change.) Please fix, other quickstarts look good.

**Comment by zepfred** [comment]
> Spring Boot quickstart is partially broken. (Possibly unrelated to this change.) Please fix, other quickstarts look good.

Good catch! The query param is required by default in Spring-boot.
analysis

**Review by triceo — APPROVED** [review]

**Pull request merged**
