### PR TITLE
chore: remove deprecated constraint configuration

### PR DESCRIPTION
**Pull request by triceo**
## Description of the change

Applies https://github.com/TimefoldAI/timefold-solver/pull/946 to quickstarts.

### Development

- [x] The changes have been covered with tests, if necessary.
- [x] You have a green build, with the exception of the flaky tests.
- [x] UI and JS files are fully tested, the user interface works for all modules affected by your changes (e.g., solve and analyze buttons).
- [x] The network calls work for all modules affected by your changes (e.g., solving a problem).
- [x] The console messages are validated for all modules affected by your changes.

### Code Review

- [x] This pull request includes an explanatory title and description.
- [x] The GitHub issue is linked.
- [ ] At least one other engineer has approved the changes.
- [ ] After PR is merged, inform the reporter.

### CODE REVIEW

**Comment by zepfred** [comment]
The changes look good, but I wonder if we could use the new constraints override in at least one of these modules. What do you think?

**Comment by triceo** [comment]
@zepfred How would you set the override? There is no UI for that.
We could make it part of the data set, but I'm thinking let's keep the quickstarts simple.

**Comment by zepfred** [comment]
> @zepfred How would you set the override? There is no UI for that. We could make it part of the data set, but I'm thinking let's keep the quickstarts simple.

Maybe adding a default configuration that differs from the values used in the constraint provider, which would require adjusting only the tests.

I think `FacilityLocationConstraintProvider` would be a good candidate because there are only three constraints.

So, there will be no change in the UI, and the quickstart will remain simple, providing a concrete example of the feature.

**Review by rsynek — APPROVED** [review]
A lot of boilerplate code going away, good.

**Pull request merged**
