### PR TITLE
docs: Add missing enterprise section to menu links in readme files (#562)

### LINKED ISSUE #562: Menu links in readme are missing a section
In this quickstarts (and potentially others), the readme links is missing a link to the enterprise section

https://github.com/TimefoldAI/timefold-quickstarts/tree/stable/java/employee-scheduling

image

### PR DESCRIPTION
**Pull request by gocklkatz**
## Description of the change

Add the enterprise section to the menu links in the readme files where it is missing (#562).

### Development

~~- [ ] The changes have been covered with tests, if necessary.~~ 
~~- [ ] You have a green build, with the exception of the flaky tests.~~ 
~~- [ ] UI and JS files are fully tested, the user interface works for all modules affected by your changes (e.g., solve and analyze buttons).~~ 
~~- [ ] The network calls work for all modules affected by your changes (e.g., solving a problem).~~ 
~~- [ ] The console messages are validated for all modules affected by your changes.~~ 
--> not relevant for a pure documentation change

### Code Review

- [x] This pull request includes an explanatory title and description.
- [x] The GitHub issue is linked.
- [ ] At least one other engineer has approved the changes.
- [ ] After PR is merged, inform the reporter.

### CODE REVIEW

**Comment by triceo** [comment]
Hello @gocklkatz!
Thank you for your pull request. Would you mind rebasing it on the `development` branch?
The `stable` branch doesn't receive commits; we only merge to it once every release.

**Comment by gocklkatz** [comment]
Hi @triceo,

yes, I'll do that. I'm on a business trip right now and I don't have access
to my Github account so I do it on Thursday.

**Comment by gocklkatz** [comment]
Hi @triceo,
sorry for the mess. I took a wrong turn. But now it adds the one relevant commit to `development` branch. If we want a PR with a clean history I can create a new PR.

**Review by triceo — APPROVED** [review]
Thank you for your work, @gocklkatz! I will squash, so history doesn't matter.

**Pull request merged**
